language: node_js
node_js:
  - "node"
deploy:
  - provider: script
    skip_cleanup: true
    script:
     - npx semantic-release
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "dist/objectarray.min.js"
    skip_cleanup: true
    on:
      tags: true
