language: node_js
node_js:
  - "node"
before_deploy:
- npm run prepub
deploy:
  - provider: script
    skip_cleanup: true
    script:
     - npx semantic-release
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - "dist/objectarray.min.js"
      - "docs/*"
    skip_cleanup: true
    on:
      tags: true
